name: Linting

on: [push, pull_request]

jobs:
  flake8-lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: flake8 Lint
        uses: py-actions/flake8@v1
